executor: slurm
use-conda: True
jobs: 10
printshellcmds: True
restart-times: 0
default-resources:
  nodes: 1
  ntasks: 1
  mem_mb: 8000
  slurm_partition: "'global'"
  slurm_extra: "'--qos=short'"
  runtime: 180  # 3h
  tmpdir: "'/scr/aherrera'"
