REFERENCE_TREE:
  "https://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/2022/06/15/public-2022-06-15.all.masked.pb.gz"
PROBLEMATIC_VCF:
  "https://github.com/W-L/ProblematicSites_SARS-CoV2/raw/master/problematic_sites_sarsCov2.vcf"
REFERENCE_FASTA:
  "data/reference.fasta"
INPUT_DIR:
  "input"
OUTPUT_DIR:
  "output"
MIN_PROP:
  - 0.9
MIN_SIZE:
  - 2
SPACE_REPLACEMENT:
  "__WS__"
METADATA_COLS:
  FULL_METADATA:
    ORIGINAL_ID: "Virus name"
    UNIQUE_ID: "Accession ID"
    DATE: "Collection date"
    LOCATION: "Location"
    GENDER: "Gender"
    LINEAGE: "Pango lineage"
    AGE: "Patient age"
FITNESS_PADDING_DAYS:
  - 0
  - 7
