__default__:
  qos: short
  name: job
  time: 03:00:00
  nodes: 1
  cpus: 1
  mem: 8G
  out: slurm-transcluster-%j_%x.out
get_problematic_vcf:
  name: dv
get_reference_tree:
  name: dt
extract_records:
  name: ex
  time: 06:00:00
  mem: 16G
phylogenetic_placement:
  name: pp
  cpus: 32
  mem: 16G
  time: 1-00:00:00
build_phylo4:
  name: p4
  mem: 16G
  time: 1-00:00:00
calculate_clusters:
  name: cc
  cpus: 16
  qos: medium
  mem: 16G
  time: 7-00:00:00
