name: Releases

on: 
  push:
    branch:
      - main
    tags:
      - "v*"

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
